### ISSUE TITLE
docker-compose currently broken

### ISSUE THREAD

**Issue by axelhodler** [OpenMined/PySonar#38]
Running `docker-compose up` fails with

```
pysonar-notebooks_1  | Traceback (most recent call last):
pysonar-notebooks_1  |   File "/usr/bin/jupyter-notebook", line 11, in <module>
pysonar-notebooks_1  |     sys.exit(main())
pysonar-notebooks_1  |   File "/usr/lib/python3.6/site-packages/jupyter_core/application.py", line 267, in launch_instance
pysonar-notebooks_1  |     return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
pysonar-notebooks_1  |   File "/usr/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
pysonar-notebooks_1  |     app.initialize(argv)
pysonar-notebooks_1  |   File "<decorator-gen-7>", line 2, in initialize
pysonar-notebooks_1  |   File "/usr/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
pysonar-notebooks_1  |     return method(app, *args, **kwargs)
pysonar-notebooks_1  |   File "/usr/lib/python3.6/site-packages/notebook/notebookapp.py", line 1296, in initialize
pysonar-notebooks_1  |     self.init_webapp()
pysonar-notebooks_1  |   File "/usr/lib/python3.6/site-packages/notebook/notebookapp.py", line 1120, in init_webapp
pysonar-notebooks_1  |     self.http_server.listen(port, self.ip)
pysonar-notebooks_1  |   File "/usr/lib/python3.6/site-packages/tornado/tcpserver.py", line 142, in listen
pysonar-notebooks_1  |     sockets = bind_sockets(port, address=address)
pysonar-notebooks_1  |   File "/usr/lib/python3.6/site-packages/tornado/netutil.py", line 197, in bind_sockets
pysonar-notebooks_1  |     sock.bind(sockaddr)
pysonar-notebooks_1  | OSError: [Errno 99] Address not available
pysonar_pysonar-notebooks_1 exited with code 1
```

Issue was found by adamchen in slack and reproduced by me

running `docker-compose up` in the `openmined/mine.js` repo works fine.

**Comment by MtDersvan** [comment]
True, what's the fix/workaround for now?

**Comment by axelhodler** [comment]
for now you can clone https://github.com/openmined/mine.js and run `docker-compose up` in there
